title: Ahsutoss Das
email: adas025@fiu.edu
description: Ph.D. Candidate in Finance at Florida International University
baseurl: ""
url: "https://ahsutossdas.github.io"
theme: minima
markdown: kramdown
